CLI improvements
runtimeverification/mir-semantics pull request #270
Opened 2023-11-24 06:14 UTC by dkcumming

This PR:
- changes default output for `parse` and `run` to `pretty`  so that the flag can be omitted
- removes flag `--spec-file` for positional argument `spec_file`

2023-11-28 02:16 UTC, yanliu18 requested changes

2023-11-28 02:23 UTC, dkcumming commented on kmir/Makefile
> +        --numprocesses=4 --durations=0 --maxfail=1 --verbose $(TEST_ARGS) \
From going through the [documentation here](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html), this seemed to be the way to use the fixtures. I did try to see if there was a way to manually split the reports for the provided tests also but I didn't see a way of doing that. @tothtamas28 do you have any recommendation for how to achieve both?

2023-11-29 08:58 UTC, tothtamas28 commented on kmir/Makefile
> +        --numprocesses=4 --durations=0 --maxfail=1 --verbose $(TEST_ARGS) \
> do you have any recommendation for how to achieve both?

The options I see are:
1. Do not build the definition as part of test setup, but before that as a manual step. Then run the tests separately.
2. Run all tests in a single run, post-process the test report.

If you choose (2), consider outputting the test report in some structured format: https://docs.pytest.org/en/latest/how-to/output.html

2023-12-07 05:28 UTC, yanliu18 commented
@dkcumming thanks. The short summary looks good. Would it be possible to add a bit more information?
For example, line 11500 in the [test report](https://github.com/runtimeverification/mir-semantics/actions/runs/7083153222/job/19275076824?pr=270#step:5:11500) is 
```SKIPPED [767] src/tests/integration/test_parse.py:55: Skipped```

can it be the following:
```SKIPPED [767/2550] src/tests/integration/test_parse.py::test_compiletest```

2023-12-07 06:01 UTC, dkcumming commented
@yanliu18 I think added the passed tests is definitely not what we want, as I mentioned above it will list them all individually, so that is hundreds maybe thousands of lines of 
```
PASSED src/tests/integration/test_name
```

2023-12-07 06:45 UTC, yanliu18 commented
@dkcumming  Sorry, a mistake. I meant `-ra`.

2023-12-08 00:58 UTC, dkcumming commented
@yanliu18 Okay I thought you meant `-rsp` again, I think I saw `-rs_` and didn't register the `a` at the end. If you agree that `-ra` is best can you approve?

2023-12-08 03:00 UTC, yanliu18 commented
OK, I can approve this change.
There should be a better way of setting up the tests when the [refactor PR](https://github.com/runtimeverification/mir-semantics/pull/283) is done.
Can you update the branch?

2023-12-11 01:33 UTC, yanliu18 approved these changes

2023-12-11 01:59 UTC, merged